USE [dw2_dw]
GO
BEGIN TRANSACTION
CREATE PARTITION FUNCTION [factpf](int) AS RANGE LEFT FOR VALUES (N'50000')


CREATE PARTITION SCHEME [factps] AS PARTITION [factpf] TO ([PRIMARY], [new])






ALTER TABLE [dbo].[factSales] DROP CONSTRAINT [PK__factSale__22E32456130E020B] WITH ( ONLINE = OFF )


ALTER TABLE [dbo].[factSales] ADD PRIMARY KEY CLUSTERED 
(
	[FactKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [factps]([FactKey])








COMMIT TRANSACTION
